AllCops:
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - calcifer.gemspec

Metrics/ModuleLength:
  Exclude:
    - spec/**/*.rb

Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 20